# Override the generated full name
fullnameOverride: "openport-exporter"
# Optional shorter name override
nameOverride: ""

# The container image to deploy
image:
  repository: ghcr.io/renatogalera/openport-exporter
  # If empty, the chart's appVersion will be used
  tag: ""
  pullPolicy: IfNotPresent
  # For private registries
  pullSecrets: []
  # - name: my-regcred

# Replica count for the Deployment
replicaCount: 1

# Port the container will LISTEN on (exporter binds to LISTEN_PORT env)
listenPort: 9919

# HTTP metrics path
metrics:
  path: /metrics

# Deployment-level annotations/labels
deploymentAnnotations: {}
deploymentLabels: {}

# Pod-level annotations/labels
podAnnotations: {}
podLabels: {}

# Pod disruption budget settings
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: ""

# Kubernetes service account
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

# Add environment variables that the container should use
extraEnv: []
# - name: EXAMPLE_ENV
#   value: "someValue"

# Optional extra args passed to the exporter
extraArgs: []
# Exporter flags (examples — uncomment as needed):
# - --log.level=info                 # debug|info|warn|error
# - --log.format=json                # text|json
# - --metrics.path=/metrics
# - --listen.port=9919
# - --address=localhost
# - --config.path=/app/config.yaml
# - --collector.go                   # enable Go runtime metrics
# - --collector.build_info=false     # disable build_info collector
# Prober flags (legacy; prefer config.targets/scheduler/modules)
# - --prober.enable
# - --prober.allow_cidr=192.168.0.0/16
# - --prober.client_allow_cidr=10.0.0.0/8

# Resource requests and limits
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Node scheduling
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""

# SecurityContext at the Pod level
podSecurityContext: {}

# Container SecurityContext
containerSecurityContext: {}

# Readiness and Liveness probes configuration
readinessProbe:
  enabled: true
  path: "/-/ready"
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  enabled: true
  path: "/-/healthy"
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

# Ingress configuration
ingress:
  enabled: false
  className: ""
  # Prefer the list form; 'host' kept for backwards compatibility
  host: "openport.example.com"
  hosts: []
  #  - host: openport.example.com
  #    paths:
  #      - path: /
  #        pathType: Prefix
  annotations: {}
  tls: []
  #  - hosts: ["openport.example.com"]
  #    secretName: openport-tls-cert

# Service configuration
service:
  type: ClusterIP
  port: 9919
  annotations: {}
  labels: {}
  # nodePort: 309919   # if type=NodePort

# Prometheus ServiceMonitor configuration
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}
  namespace: ""
  # Advanced relabelings (optional)
  relabelings: []
  metricRelabelings: []

# Additional labels and annotations for the ConfigMap (optional)
configMap:
  labels: {}
  annotations: {}

# Config file data mapped to config.yaml
config:
  server:
    port: 9919
    trusted_proxies_cidrs: []
  scanning:
    interval: 10800
    port_range: "1-65535"
    max_cidr_size: 24
    timeout: 3600
    duration_metrics: false
    disable_dns_resolution: true
    udp_scan: false
    use_syn_scan: true
    # Legacy worker knobs (scheduler.* is preferred but used as fallback)
    rate_limit: 60
    task_queue_size: 100
    worker_count: 5
    # Nmap tuning
    min_rate: 1000
    max_rate: 0
    min_parallelism: 1000
    max_retries: 6
    host_timeout: 300
    scan_delay: 0
    max_scan_delay: 0
    initial_rtt_timeout: 0
    max_rtt_timeout: 0
    min_rtt_timeout: 0
    disable_host_discovery: true

  # Authentication for Tasks API (optional)
  auth:
    bearer_token: ""
    basic:
      username: ""
      password: ""

  # Background targets (module is currently ignored by background scheduler)
  targets:
    - name: "dmz_ssh"
      target: "192.168.1.0/24"
      port_range: "22"
      protocol: "tcp"
      interval: "1h"
      module: "tcp_syn_fast"
    - name: "branch_web"
      target: "10.0.0.0/24"
      port_range: "80,443"
      protocol: "tcp"
      interval: "2h"
      module: "tcp_connect_safe"

  # Optional allowlisted detailed per-port series (bounded by budget)
  # background_details:
  #   enabled: true
  #   series_budget: 2000
  #   ttl: "30m"
  #   include_alias: true
  #   include_ip: true
  #   targets:
  #     - alias: "ssh-bastion-primary"
  #       cidr: "203.0.113.10/32"
  #       protocol: "tcp"
  #       ports: ["22"]

  policy:
    client_allow_cidrs: ["127.0.0.0/8"]
    rate_limit_rps: 2.0
    rate_burst: 2
    max_concurrent: 2
    series_limit: 250000

  scheduler:
    worker_count: 5
    task_queue_size: 100
    default_timeout: "30m"
    default_max_cidr_size: 24
    dedupe_ttl: "15m"
    task_gc_max: 10000
    task_gc_max_age: "24h"
    module_limits:
      default: 0
      tcp_syn_fast: 2

  modules:
    tcp_syn_fast:
      protocol: tcp
      ports: "22,80,443,1000-1024"
      use_syn_scan: true
      min_rate: 2000
      min_parallelism: 1000
      max_retries: 3
      host_timeout: 180
      disable_host_discovery: true
    tcp_connect_safe:
      protocol: tcp
      ports: "22,80,443"
      use_syn_scan: false
      max_retries: 2
      host_timeout: 120

