# Server configuration
server:
  port: 9919

# Scanning configuration  
scanning:
  interval: 86400
  port_range: "1-65535"
  max_cidr_size: 24
  timeout: 3600
  duration_metrics: false
  disable_dns_resolution: true

# Performance configuration
  rate_limit: 30
  task_queue_size: 1000
  worker_count: 10
  min_rate: 1500 # Increases the minimum packet rate per second
  max_rate: 0 # No maximum limit (0 or clear to disable)
  min_parallelism: 1200 # Increases the minimum parallelism
  max_retries: 5 # Decreases the maximum number of retries
  host_timeout: 240 # Decreases the per-host timeout to 4 minutes
  scan_delay: 1 # Adds a small delay between probes (in ms)
  max_scan_delay: 10 # Maximum adjustable delay (in ms)
  initial_rtt_timeout: 100 # Initial RTT timeout (in ms)
  max_rtt_timeout: 2000 # Maximum RTT timeout (in ms)
  min_rtt_timeout: 50 # Minimum RTT timeout (in ms) ms)
  disable_host_discovery: true # Disable host discovery (-Pn) for faster speed (if applicable)