apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openport-exporter.fullname" . }}-config
{{- if .Values.configMap.annotations }}
  annotations:
{{- toYaml .Values.configMap.annotations | nindent 4 }}
{{- end }}
{{- if .Values.configMap.labels }}
  labels:
    {{- toYaml "openport-exporter.labels" . | nindent 4 }}
{{- end }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
