apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openport-exporter
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openport-exporter
            port:
              number: 9919
