{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "openport-exporter.fullname" . }}
{{- if .Values.podDisruptionBudget.labels }}
  labels:
{{- toYaml "openport-exporter.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.podDisruptionBudget.annotations }}
  annotations:
{{- toYaml .Values.podDisruptionBudget.annotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openport-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
