apiVersion: v1
kind: Service
metadata:
  name: openport-exporter
  labels:
    app: openport-exporter
spec:
  ports:
  - port: 9919
    targetPort: 9919
  selector:
    app: openport-exporter
  type: ClusterIP
