apiVersion: v1
kind: Service
metadata:
  name: {{ include "openport-exporter.fullname" . }}
  {{- if .Values.service.labels }}
  labels:
    {{- toYaml "openport-exporter.labels" . | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.server.port }}
  selector:
    app.kubernetes.io/name: {{ include "openport-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
