name: Bump Chart Values on Tag

on:
  workflow_dispatch:

concurrency:
  group: bump-values-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - run: go build ./...
      - run: go test -v ./...

  bump-values:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write
      pull-requests: write
    env:
      CHART_DIR: chart
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set version var
        id: vars
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Install yq
        uses: mikefarah/yq@v4

      - name: Update values.yaml (image.tag) and Chart.yaml (appVersion)
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          set -euo pipefail
          test -f "$CHART_DIR/values.yaml"
          test -f "$CHART_DIR/Chart.yaml"
          yq -i '.image.tag = env(VERSION)' "$CHART_DIR/values.yaml"
          yq -i '.appVersion = env(VERSION)' "$CHART_DIR/Chart.yaml"
          echo "Updated image.tag and appVersion to ${VERSION}"

      - name: Commit and push bump branch (open PR manually)
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          CHART_DIR: ${{ env.CHART_DIR }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BR="chore/bump-chart-to-${VERSION}"
          git checkout -b "$BR"
          git add "$CHART_DIR/values.yaml" "$CHART_DIR/Chart.yaml"
          if git diff --cached --quiet; then
            echo "No chart changes to commit. Skipping push."
          else
            git commit -m "chore(chart): bump image.tag & appVersion to ${VERSION} [skip ci]"
            git push -u origin "$BR"
            echo "::notice title=Open PR::https://github.com/${GITHUB_REPOSITORY}/compare/main...${BR}?expand=1"
          fi
