name: Bump Chart Values on Tag

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: bump-values-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  test:
    name: Go Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - run: go build ./...
      - run: go test -v ./...

  bump-values:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: write
      pull-requests: write
    env:
      CHART_DIR: charts/openport-exporter
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set version var
        id: vars
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Install yq
        uses: mikefarah/yq@v4

      - name: Update values.yaml (image.tag) and Chart.yaml (appVersion)
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          set -euo pipefail
          test -f "$CHART_DIR/values.yaml"
          test -f "$CHART_DIR/Chart.yaml"
          yq -i '.image.tag = env(VERSION)' "$CHART_DIR/values.yaml"
          yq -i '.appVersion = env(VERSION)' "$CHART_DIR/Chart.yaml"
          echo "Updated image.tag and appVersion to ${VERSION}"

      - name: Raise pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(chart): bump image.tag & appVersion to ${{ steps.vars.outputs.version }} [skip ci]"
          branch: "chore/bump-chart-to-${{ steps.vars.outputs.version }}"
          title: "chore(chart): bump image.tag & appVersion to ${{ steps.vars.outputs.version }}"
          body: |
            Bumps Helm chart values to `${{ steps.vars.outputs.version }}`:
            - `values.yaml: image.tag`
            - `Chart.yaml: appVersion`

            Triggered by tag `${{ steps.vars.outputs.version }}`.
          labels: chart, automation, release
          base: main
