name: CI

on:
  pull_request:
    branches: ["**"]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  dockerfile_lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Detect Dockerfile changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'
              - '.hadolint.yaml'
      - name: Hadolint
        if: steps.changes.outputs.dockerfile == 'true'
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
          failure-threshold: error

  lint_test:
    name: Lint + Vet + Vuln + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: golangci-lint (v2)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          only-new-issues: true

      - name: go vet
        run: go vet ./...

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Unit tests (race + cover)
        run: |
          set -euo pipefail
          go test -race -shuffle=on -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage.out
          path: coverage.out
          if-no-files-found: ignore
          retention-days: 7

  meta_lint:
    name: Lint de Workflows (actionlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: reviewdog/action-actionlint@v1
